server:
  port: 8080

spring:
  application.name: consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
logging:
  level:
    root: OFF
    org.springframework: OFF
    org.apache.kafka: OFF