spring:
  application.name: processor
  cloud:
    stream:
      bindings:
        enhanceMessage-in-0:
          destination: raw-message
          group: kafka-mini-game
        enhanceMessage-out-0:
          destination: message
          group: kafka-mini-game
      kafka:
        binder:
          brokers: localhost:9092