server:
  port: 8080

spring:
  application.name: controller
  cloud:
    stream:
      bindings:
        sendMessage-out-0:
          destination: raw-message
          group: kafka-mini-game
      kafka:
        binder:
          brokers: localhost:9092